PROJECT_NAME: DSI

MAX_EPOCHS: 20
BSZ: 30
LR: 15e-5
USE_LR_SCHEDULER: True
MAX_LEN: 32
INDEXING_RETRIEVAL_RATIO: 32

LOGGER: tensorboard

PATHS:
  ckpt_dir: ckpt/
  logs: logs/

RAW_DATA:
  query: data/raw/hotpotqa/queries.jsonl
  corpus: data/raw/hotpotqa/corpus.jsonl
  train: data/raw/hotpotqa/qrels/train.tsv
  val: data/raw/hotpotqa/qrels/dev.tsv
  test: data/raw/hotpotqa/qrels/test.tsv

INTERIM:
  docid:
    tokens: data/interim/gen_retrieval/docid/corpus_tokens_[proc_id].npz
    embds: data/interim/gen_retrieval/docid/corpus_embds.pt

PROCESSED:
  query: data/processed/gen_retrieval/query_tokenized.parquet
  corpus: data/processed/gen_retrieval/corpus_tokenized.parquet
  semantic_docid: data/processed/gen_retrieval/semantic_ids.pkl

MODEL_DOCID: res/bert-base-cased
MODEL_GENERATIVE: res/t5-large

NEW_TOKENS_DICT:
  task_indexing_tok: <IDX>
  task_retrieval_tok: <RTRV>
  sep_tok: <sep>
