# coding: utf-8

"""
    xButler webserver

    Web server for ML services of xButler

    The version of the OpenAPI document: 1.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from openapi_server.apis.resource_api import router as ResourceApiRouter
from openapi_server.apis.retrieval_api import router as RetrievalApiRouter

app = FastAPI(
    title="xButler webserver",
    description="Web server for ML services of xButler",
    version="1.1.0",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

app.include_router(ResourceApiRouter)
app.include_router(RetrievalApiRouter)
