MODEL_NAME: bert-base-cased
Nq: 32
BSZ: 32
D_HID: 128
D_HID_BERT: 768
NUM_EPOCHS: 10
LR: 3e-4

LOGGER: wandb

PATHS:
  tokenizer: data/processed/colbert/tokenizer
  punctuations: data/processed/colbert/punctuations.json
  ckpt: ckpt/
  logs: logs/

RAW_DATA:
  query: data/raw/hotpotqa/queries.jsonl
  corpus: data/raw/hotpotqa/corpus.jsonl
  train: data/raw/hotpotqa/qrels/train.tsv
  val: data/raw/hotpotqa/qrels/dev.tsv
  test: data/raw/hotpotqa/qrels/test.tsv

PROCESSED:
  query: data/processed/colbert/query_tokenized.parquet
  corpus: data/processed/colbert/corpus_tokenized_[i].parquet

TOKEN:
  query: "[Q]"
  document: "[D]"
